### ISSUE TITLE
Documentação de contexto - Introdução

### ISSUE THREAD

**Issue by anacfassis** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t1-dicas-de-viagem#1]

**Comment by danielaferassis** [comment]
### INTRODUÇÃO
Você é dono de pet mineiro e já quis levar o seu pet para uma viagem, mas não soube nem por onde começar? A proposta do MEU PET VIAJA veio te ajudar nessa jornada!

O **problema** é a falta de informação relevante, confiável e atualizada sobre as regras e cuidados para se viajar com o pet e as hospedagens *pet friendly*, em Minas Gerais. O **objetivo** principal desse projeto é tornar acessível essas informações aos donos de pet através de uma aplicação web (um site) garantindo, assim, que eles tenham facilidade em programar o destino da viagem sem ter que deixar um importante membro da família para trás.

Ademais, os nossos objetivos específicos são: identificar e coletar informações sobre regras de viagem com pets em companhias aéreas, de ônibus e traslado em carro particular; identificar e listar hotéis, pousadas e airbnbs em Minas Gerais que aceitem a hospedagem de animais de estimação; e identificar e listar serviços e pontos turísticos de cidades mineiras que permitam o acesso de animais de estimação.

Esse problema já não pode ser mais ignorado, já que, atualmente, um grande número de brasileiros são donos de pets e na pandemia esse número só aumentou, como mostrou a pesquisa Radar Pet 2021, realizada pela Comac. Com isso, é de se pensar que ao viajar essas pessoas gostariam de levar seus queridos pets, e o site Booking mostrou exatamente isso em uma pesquisa de 2019. Foram 22 mil entrevistados, dos quais 51% declarou que só viajariam em 2020 se pudessem levar seus pets, e 59% aceitaria pagar mais caro em acomodações *pet friendly*.
